"""BDB Audit v2 Finding Adjudication and Contradiction module (M21/M22/WP-F4-08)."""
from .models import (
    FindingClaimRevision,
    FindingAxisAssessment,
    FindingAdjudicationDecision,
    RootCauseRevision,
    ContradictionRevision,
    ContradictionResolutionDecision,
    AXIS_DOMAINS,
    EPISTEMIC_OUTCOMES,
    FINDING_LIFECYCLE_STATUSES,
    CONTRADICTION_STATUSES,
    sort_membership_edges,
)
from .engine import (
    validate_root_cause_authority,
    validate_finding_adjudication_rules,
    adjudicate_finding,
    transition_finding_lifecycle,
    resolve_contradiction,
    apply_contradiction_resolution,
    reopen_contradiction,
    cluster_findings_into_root_cause,
    ALLOWED_LIFECYCLE_TRANSITIONS,
)
from .contribution import (
    ProducerContribution,
    ContributionProjection,
    build_contribution_projection,
    validate_contribution_authority,
)

__all__ = [
    "FindingClaimRevision",
    "FindingAxisAssessment",
    "FindingAdjudicationDecision",
    "RootCauseRevision",
    "ContradictionRevision",
    "ContradictionResolutionDecision",
    "AXIS_DOMAINS",
    "EPISTEMIC_OUTCOMES",
    "FINDING_LIFECYCLE_STATUSES",
    "CONTRADICTION_STATUSES",
    "sort_membership_edges",
    "validate_root_cause_authority",
    "validate_finding_adjudication_rules",
    "adjudicate_finding",
    "transition_finding_lifecycle",
    "resolve_contradiction",
    "apply_contradiction_resolution",
    "reopen_contradiction",
    "cluster_findings_into_root_cause",
    "ALLOWED_LIFECYCLE_TRANSITIONS",
    "ProducerContribution",
    "ContributionProjection",
    "build_contribution_projection",
    "validate_contribution_authority",
]
